### ISSUE TITLE
BeFake changed Friends Feed!

### ISSUE THREAD

**Issue by bengram** [rvaidun/befake#104]
Hello,

new bereal update changes FEED API from 
https://mobile.bereal.com/api/feeds/friends
to
https://mobile.bereal.com/api/feeds/friends-v1

MAKE TO POSSIBLE to post 3 BeReal per Day

**Comment by rvaidun** [comment]
?
Friends feed seems to work right now

**Comment by bengram** [comment]
yeah, it work but friends who postet 3 bereal on one day, you can only see 1 bereal with the old friends feed api, you have to use friends-v1

**Comment by U14-dev** [comment]
Working on a update for the new feed rn, will commit later^
