### ISSUE TITLE
See the second bereal

### ISSUE THREAD

**Issue by meand0** [rvaidun/befake#112]
Since the last update it is allowed to upload up to 3 images, but on the web you can only see the first one, is there a way to see all of them?

**Comment by xKRISTOFx** [comment]
[PR#84](https://github.com/rvaidun/befake/pull/84)

**Comment by rvaidun** [comment]
https://befake-623af--pr114-dev-ydr1g3er.web.app/
This is a development URL but it allows you to see multiple bereals. There are known bugs in this version.

**Comment by rvaidun** [comment]
Fixed
