### ISSUE TITLE
Uk number no auth

### ISSUE THREAD

**Issue by Naocchi95** [rvaidun/befake#116]
Entering Uk number does not sent a code nor prompt the website to enter a code. Before this, I noticed an issue which previously was marked as complete: internal server error, which with UK numbers was never fixed as this issue persisted until this new issue appeared.

**Comment by TFKNazGul** [comment]
Don't use link with www.
Same for switzerland. 
If I try login from https:://www.befake.fr give me the same error.

Using https://befake.fr everything works fine.

Test it 😁

**Comment by Naocchi95** [comment]
> Don't use link with [www](http://www). Same for switzerland. If I try login from https://www.befake.fr give me the same error.
> 
> Using https://befake.fr everything works fine.
> 
> Test it 😁

Just tried this but still the same issue
