### ISSUE TITLE
Logged in but: Error! Something went wrong while getting posts

### ISSUE THREAD

**Issue by Laceh** [rvaidun/befake#118]
<img width="1440" alt="image" src="https://github.com/rvaidun/befake/assets/37019949/05b565b2-034d-4640-be56-ce3d21c28370">
Getting the error on the bottom left corner: Error! Something went wrong while getting posts

And in the network when the request is being made to 
https://warm-scrubland-06418.herokuapp.com/https://mobile.bereal.com/api/person/me

It is giving Status Code: 404 Not Found

Anyone got a fix for this? When I log in on another account it is giving me the normal website. But on my account it isn't.

<img width="1440" alt="image" src="https://github.com/rvaidun/befake/assets/37019949/921f2b11-5657-4197-bedd-0102dfafed28">

**Comment by Laceh** [comment]
Anyone got an idea to fix?

**Comment by rvaidun** [comment]
This happens to me too. I just reload the page a couple times and eventually I'm able to see the posts. I'm honestly not sure why this but happens
