### ISSUE TITLE
Site reloads every 60 secoends

### ISSUE THREAD

**Issue by LOGODERKING** [rvaidun/befake#123]
I host the befake on my vps with nginx. But every 60 seconds the tab reloads. It's not  bug or something but its annoying for me. Especially if i want to post my bereal etc. Is there any way to fix that?

I keep the website only by a systemd file.

`/etc/systemd/system/befake.service`
```
[Unit]
Description=Befake-Server
After=nginx.service

[Service]
WorkingDirectory=/var/www/befake
ExecStart=/usr/bin/npm run dev
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by rvaidun** [comment]
have no idea honestly but FYI `npm run dev` starts a development server not intended for a prod environment or anything. you'd probably want to run `npm run build` which will generate the `dist` folder that contains the raw javascript and html. then u can point ur nginx server to the index.html file in the dist folder.

**Comment by LOGODERKING** [comment]
ok i did now what you said but i cant get nginx to get the file. I get either a white screen with the error in the console: Failed to load resource: the server responded with a status of 404 (). or the screen with welcome to nginx. Can you help me with that?
My nginx.conf file looks like this:

```
server {
    if ($host = DOMAIN) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name DOMAIN;
    return 301 https://$server_name$request_uri;


}

server {
    listen 443 ssl http2;
    server_name DOMAIN;

    root /var/www/befake;
    index index.html;

    listen [::]:443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/DOMAIN/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/DOMAIN/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = DOMAIN) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name DOMAIN;
    listen 80;
    return 404; # managed by Certbot
}
```
I replaced btw. my domain with the word Domain here.

**Comment by rvaidun** [comment]
idk i've never worked with nginx before. maybe root should be set to /var/www/befake/dist? not sure
