### ISSUE TITLE
TypeError: Unable to Fetch

### ISSUE THREAD

**Issue by Galaxiumm** [rvaidun/befake#125]
I have used befake sometime now, but after the original domain was wiped out and i had to use new ones, i haven't been able to login normally. After I put my phone number either the page doesn't load and states this error or i get sent to the put the OTP code and i don't recieve any.

I am from Spain so maybe this is a country problem?

**Comment by Natbrgm10** [comment]
Same here. The page is blank. I do not even have the option to write my phone number. 
I am also from Spain. It might be a country problem, as you said...
