### ISSUE TITLE
Can't switch between bonus bereal comments

### ISSUE THREAD

**Issue by Saiitama** [rvaidun/befake#128]
So in the past, if someone posted a bereal and a bonus one (second or third) i could see the comments and emoji of each one by chooshing what bereal to see, and the comment section/emoji would swap with it, now it's bugged, i usually see only the comment section of the first posted bereal even if i'm viewing the photo of the second/third bereal

**Comment by rvaidun** [comment]
It still switches for me. Can't reproduce this
