### ISSUE TITLE
Is there a way to use this to see a user's memories?

### ISSUE THREAD

**Issue by ajwwiolufliu** [rvaidun/befake#129]

**Comment by TFKNazGul** [comment]
This will be excellent feature if @rvaidun can make it possible.

**Comment by rvaidun** [comment]
Implemented in latest version

**Comment by TFKNazGul** [comment]
@rvaidun Is not possible to see old posts from our friends?
Like memories but from our friend list ?

**Comment by rvaidun** [comment]
No, this is impossible since as far as I am aware the API does not let you see other users memories.
