### ISSUE TITLE
Friends of friends posts request

### ISSUE THREAD

**Issue by mast-and** [rvaidun/befake#133]
It would be great to see the postings of my friends' friends. Since the new update implements this.

**Comment by rvaidun** [comment]
How are you able to see it?

**Comment by meand0** [comment]
![image](https://github.com/rvaidun/befake/assets/91870390/dc804bed-e28b-40f1-ae19-3a059cee067b)
At the top of the page, after you post a bereal, the "friends of friends" options will appear.

**Comment by meand0** [comment]
Is it posible to have this into the app?

**Comment by Ein-Tim** [comment]
@dominik-pm This feature isn't even live in BeReal, right?

**Comment by Breathix** [comment]
it is but it would be cool to see it added in befake

**Comment by Ein-Tim** [comment]
@Breathix I can't access this feature in BeReal.

**Comment by meand0** [comment]
> https://github.com/notmarek/BeFake has this feature

code has been removed due to c&d

**Comment by GWPvGWP** [comment]
Any plans for this feature?

Maybe anyone who still has code from notmarek?

**Comment by rvaidun** [comment]
From what I remember the endpoint was `https://mobile.bereal.com/api/feeds/friends-of-friends` but this endpoint is giving me a 403 Error.

I also haven't seen this feature on the official app so I have no way of reverse engineering it.

**Comment by U14-dev** [comment]
live now^

**Comment by macedonga** [comment]
You just have to add to the query the "page" argument.
So the url for the request with the next token given to you by the api (which btw is just some base64 encoded json object) will look like this: `https://mobile.bereal.com/api/feeds/friends-of-friends?page={nextTokenHere}`

To see how this and other endpoints work, just disassemble the base.apk file from the apkm file you can download from apkmirror :-)

Also (i know, shameless plug), if you don't feel like coding it in your fork yourself, you can check out my bereal client on here: [BeUnblurred](https://beunblurred.co). (it's open source ;-D)

**Comment by Breathix** [comment]
looks sick, I'll try it asap

**Comment by U14-dev** [comment]
Ah yes, i'm on vacation right now so I haven't been able to take a close look at the update yet. Your client looks good tho^

**Comment by macedonga** [comment]
> Ah yes, i'm on vacation right now so I haven't been able to take a close look at the update yet. Your client looks good tho^  

Thanks :-)

**Comment by macedonga** [comment]
> `https://mobile.bereal.com/api/feeds/friends-of-friends?page={nextTokenHere}`

It now looks that that endpoint returns 0 posts if you haven't posted a public BeReal.

**Comment by U14-dev** [comment]
Yep and they also fixed switching to private multiple times a day: 
![Screenshot_20230830-195524_Gallery](https://github.com/rvaidun/befake/assets/58476413/aa6d85b6-cdf6-480f-b7df-0af33791658a)

**Comment by ImBadTomas** [comment]
You have to post a bereal and have that enabled in your bereal to see friends of friends
