### ISSUE TITLE
React to all posts feature isn't working

### ISSUE THREAD

**Issue by Maximapple** [rvaidun/befake#134]
The feature in general isn't working for me. It lets me upload a picture that should be used for the reaction and then I click on the "Upload RealMojis" button but nothing happens afterward.

Uploading a custom RealMoji on a single BeReal post works just fine though.

I've already mentioned this [here](https://github.com/rvaidun/befake/issues/39), but have not yet received a response, so I thought I'd create it's own issue for it.

**Comment by rvaidun** [comment]
fixed the issue about a week ago. i just tested it and it's working for me.
