### ISSUE TITLE
Hosting the site by Github I get a blank page, how can I fix it?

### ISSUE THREAD

**Issue by marco2407** [rvaidun/befake#141]

**Comment by touqnti** [comment]
can you please tell me how i am supposed to host the website locally please ?

**Comment by marco2407** [comment]
I made a fork and then I hosted the GitHub page, this is the link:

https://marco2407.github.io/myhost/
Il giorno mer 14 giu 2023 alle 18:34 touqnti ***@***.***> ha
scritto:
