### ISSUE TITLE
API ERROR

### ISSUE THREAD

**Issue by PIK4BOO** [rvaidun/befake#148]
I get this error when going to the location: 'Google Maps Platform rejected your request. The provided API key is invalid.' I have changed the API, but it still generates the same error. Can anyone provide me with a solution?

**Comment by GWPvGWP** [comment]
My quick fix is to replace the iframe source link with
`https://maps.google.com/maps?width=300&amp;height=300&amp;hl=en&amp;q=${this.curpost.location.latitude}, ${this.curpost.location.longitude}+(map)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed`

**Comment by rvaidun** [comment]
@GWPvGWP thank you, using this to fix it

**Comment by rvaidun** [comment]
nvm upon testing  this seems slower, just updating the API key
