### ISSUE TITLE
Improving the "react to all posts feature" and issue with the site

### ISSUE THREAD

**Issue by Maximapple** [rvaidun/befake#160]
Thank you for adding the possibility to use saved reactions!

One thing I noticed in the past is that, when using the react to all posts feature, it would override reactions I've already made on posts.

Maybe you can change it so that it only reacts to posts where I haven't added a reaction yet?

Also, I noticed that the site no longer loads successfully on my iPhone, where it has worked just fine in the past. Ok, well, it loads but after it has loaded all posts and I do something, the site crashes. On my computer it works just fine.

**Comment by rvaidun** [comment]
> Maybe you can change it so that it only reacts to posts where I haven't added a reaction yet?

Good idea will implement this in future update.
