### ISSUE TITLE
phone verification problem

### ISSUE THREAD

**Issue by baptistecrr** [rvaidun/befake#163]
huge problem, when I put the phone number, either it loads to infinity or I receive the verification numbers but it gives me an error, knowing that I have just hosted the new new version because the old one is closed visibly

**Comment by jrvgr** [comment]
Users who are already logged in such as myself can't fetch posts either

**Comment by baptistecrr** [comment]
it's the verification of the OTP that has a problem

**Comment by rvaidun** [comment]
I took down the proxy and included the proxy server locally.

**Comment by baptistecrr** [comment]
I again copied the github code on vercel.app but it still does not work, what should I do please

**Comment by heightzyt** [comment]
how do i make it work on vercel then
