### ISSUE TITLE
Error! TypeError: Failed to fetch

### ISSUE THREAD

**Issue by Feticones** [rvaidun/befake#165]
Everytime i want to enter the otp code and click verify there is this error coming

**Comment by Feticones** [comment]
i already run it on localhost:3000

**Comment by Feticones** [comment]
nvm fixed it

**Comment by Feticones** [comment]
download the befake zip, unzip it and run "npm install", then do "node  server.js" and then you can do "npm run dev" after that go on localhost:3000 and then it should work

**Comment by baptistecrr** [comment]
@Feticones 

I don't understand you have method, I use vercel app to have befake locally, can we talk in private so that you explain to me in detail how you did it? I downloaded the zip but after I am lost

**Comment by Feticones** [comment]
@baptistecrr  you can write me on discord: Fetico if you still need help

**Comment by puss2610** [comment]
> Author

you're a legend mate
