### ISSUE TITLE
Error while getting the posts and failed to fetch

### ISSUE THREAD

**Issue by madafuggie** [rvaidun/befake#167]
Running locally on Vercel app. Any solution? Logged out cuz I was getting error while getting the posts and now I can't even put my number because I get the failed to fetch error.

**Comment by baptistecrr** [comment]
don't look for the developer is incapable, he closes all discussions this pussy

**Comment by rvaidun** [comment]
@baptistecrr these discussions are not relevant as the repo does not provide solutions for hosting on third party platforms. If you wish to run the server locally you can read the [Readme.md](https://github.com/rvaidun/befake#compile-and-hot-reload-for-development) on how to do it.
