### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by Maximapple** [rvaidun/befake#168]
I'm running BeFake locally and receive the error "Type Error: Failed to fetch" after entering the OTP Code.

Console output:
![IMG_1584](https://github.com/rvaidun/befake/assets/5410641/3a44ba04-604f-4e15-af0e-3a7f14fe5ffa)

**Comment by LorDawid** [comment]
![image](https://github.com/rvaidun/befake/assets/44745662/da9e6844-bd43-4794-8728-7a36347f9050)
well, i get this output - i also cant use it locally for now.

**Comment by LorDawid** [comment]
my local installation also says 'access to fetch blocked' but in my instance it seems to be because of the CORS policy..

**Comment by rvaidun** [comment]
have you started the server at localhost:8000. In a new terminal try node server.js and make sure you see listening on 8080

**Comment by Maximapple** [comment]
Hey @rvaidun,

node server.js in a new terminal seems to have made it work. at least the login works now. didn't test any features yet, but posts of friends are loading successfully
