### ISSUE TITLE
Location Input Not Working

### ISSUE THREAD

**Issue by felixlehoang** [rvaidun/befake#17]
Is there a specific format for latitude and longitude? I tried but it’s not working, and tge post cannot be submitted.

**Comment by felixlehoang** [comment]
Can not input negative value as well, for westward of the hemisphere (USA specifically).

**Comment by rvaidun** [comment]
latitude longitude should just be numeric values. I was able to input negative numbers. Can you provide specific lat, lon coordinates that don't work? Need a little more information so I can reproduce the issue.
