### ISSUE TITLE
Mistake argument in "React to all posts"?

### ISSUE THREAD

**Issue by sisi** [rvaidun/befake#170]
Reacting with this function returns a 404 with the error "post-not-found".
I swapped the arguments for postid and postuserid,  it succeeded in returning a status code of 200.

Perhaps this change(https://github.com/rvaidun/befake/commit/5841292bb755e3c82c3aaea8557981e983b58beb) has prevented getting the correct arguments?

**Comment by rvaidun** [comment]
Fixed.
