### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by puss2610** [rvaidun/befake#177]
I notice the link to the website has been removed from the readme and the website no longer leads to anything, also when hosting (on vercel) i only get the error "Error! Something went wrong while getting posts"

**Comment by stepersy** [comment]
Same Issue. And when I try to reload the page it logout automatically

**Comment by user12312324** [comment]
Same^ is there a fix?

**Comment by ryanstickley** [comment]
I contacted the creator of the befake bot on telegram, which I think uses this code as a base and he diagnosed the error being caused due to Firebase (which bereal uses to login) and is an issue with just +44 numbers
As of now there is no fix

**Comment by rvaidun** [comment]
I am no longer hosting. To host on Vercel you'd need to modify the proxy URL to point to a cors anywhere instance accessible by https

**Comment by stepersy** [comment]
Could you please add a tutorial or a guide that illustrate how to change the proxy on Vercel? Thanks!

**Comment by rvaidun** [comment]
Sorry, I am unfamiliar with hosting on vercel and afaik there is no free way of hosting cors anywhere

**Comment by MomoCrafter2013** [comment]
> When hosting locally, it works perfectly If anyone needs a bit of a guide on how to do that (windows pc) just lmk

Could you help me pls to run it locally? Thanks

**Comment by reznofiat1** [comment]
> 

Could you add your 4 digit code for your discord ID?

**Comment by reznofiat1** [comment]
> > > When hosting locally, it works perfectly If anyone needs a bit of a guide on how to do that (windows pc) just lmk
> > 
> > 
> > Could you help me pls to run it locally? Thanks
> 
> Just send me a message on discord @ryanstickley

Could you add your 4 digit code for your discord ID?

**Comment by ryanstickley** [comment]
> > > > When hosting locally, it works perfectly If anyone needs a bit of a guide on how to do that (windows pc) just lmk
> > > 
> > > 
> > > Could you help me pls to run it locally? Thanks
> > 
> > 
> > Just send me a message on discord @ryanstickley
> 
> Could you add your 4 digit code for your discord ID?

They don't exist anymore...

**Comment by reznofiat1** [comment]
> > > > > When hosting locally, it works perfectly If anyone needs a bit of a guide on how to do that (windows pc) just lmk
> > > > 
> > > > 
> > > > Could you help me pls to run it locally? Thanks
> > > 
> > > 
> > > Just send me a message on discord @ryanstickley
> > 
> > 
> > Could you add your 4 digit code for your discord ID?
> 
> They don't exist anymore...

Are you sure? When I try to add you on discord, it asks for the 4 digit tag
