### ISSUE TITLE
Duplicate reaction feature

### ISSUE THREAD

**Issue by matt496** [rvaidun/befake#180]
I saw someone who react two times with the same emoji reaction ( there is not a graphical bug, check on app + website)
There is possible to do this
![IMG_1201](https://github.com/rvaidun/befake/assets/28789567/2a778ad6-65e1-4119-90da-7eae7d81b8d4)
![IMG_1202](https://github.com/rvaidun/befake/assets/28789567/6330dff7-1dda-4478-9b3e-b89091fbd2c3)
 feature ?

**Comment by NeedNot** [comment]
> I saw someone who react two times with the same emoji reaction ( there is not a graphical bug, check on app + website) There is possible to do this ![IMG_1201](https://user-images.githubusercontent.com/28789567/268086698-2a778ad6-65e1-4119-90da-7eae7d81b8d4.jpeg) ![IMG_1202](https://user-images.githubusercontent.com/28789567/268086700-6330dff7-1dda-4478-9b3e-b89091fbd2c3.jpeg) feature ?

that has to be a bug on bereals servers because when you post a realmoji it automatically replaces the one already there

**Comment by Leandro12341** [comment]
> I saw someone who react two times with the same emoji reaction ( there is not a graphical bug, check on app + website)
> There is possible to do this
> ![IMG_1201](https://user-images.githubusercontent.com/28789567/268086698-2a778ad6-65e1-4119-90da-7eae7d81b8d4.jpeg)
> ![IMG_1202](https://user-images.githubusercontent.com/28789567/268086700-6330dff7-1dda-4478-9b3e-b89091fbd2c3.jpeg)
> feature ?

How do you host befake
