### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by ryanstickley** [rvaidun/befake#181]

**Comment by Leandro12341** [comment]
coud you help me when I make it open with vercell app it comes something wrong while getting post

**Comment by Leandro12341** [comment]
> _No description provided._

coud you help me when I make it open with vercell app it comes something wrong while getting pos

**Comment by ryanstickley** [comment]
i didnt mean to create this issue 😭
anyway i dont think it can be hosted on vercel anymore. something to do with configuring the corsanywhere ip (not sure tbh but idk how to do it)
i had to host the server locally instead

Download and install Node.js https://nodejs.org/en/download/current
Download the github repository and extract it
Open cmd in the befake folder, or navigate to it and run "npm install"
Then everytime you need to run it navigate to the befake folder and run "npm run dev"

**Comment by Leandro12341** [comment]
> i didnt mean to create this issue 😭 anyway i dont think it can be hosted on vercel anymore. something to do with configuring the corsanywhere ip (not sure tbh but idk how to do it) i had to host the server locally instead
> 
> Download and install Node.js https://nodejs.org/en/download/current Download the github repository and extract it Open cmd in the befake folder, or navigate to it and run "npm install" Then everytime you need to run it navigate to the befake folder and run "npm run dev"

Could you show me how to do this on discord

**Comment by ryanstickley** [comment]
> > i didnt mean to create this issue 😭 anyway i dont think it can be hosted on vercel anymore. something to do with configuring the corsanywhere ip (not sure tbh but idk how to do it) i had to host the server locally instead
> > Download and install Node.js https://nodejs.org/en/download/current Download the github repository and extract it Open cmd in the befake folder, or navigate to it and run "npm install" Then everytime you need to run it navigate to the befake folder and run "npm run dev"
> 
> Could you show me how to do this on discord

whats your @

**Comment by MomoCrafter2013** [comment]
> i didnt mean to create this issue 😭 anyway i dont think it can be hosted on vercel anymore. something to do with configuring the corsanywhere ip (not sure tbh but idk how to do it) i had to host the server locally instead
> 
> Download and install Node.js https://nodejs.org/en/download/current Download the github repository and extract it Open cmd in the befake folder, or navigate to it and run "npm install" Then everytime you need to run it navigate to the befake folder and run "npm run dev"

I am getting this error when trying to run "npm run dev": Could not resolve "@vue/shared". Do you know how to fix it?
