### ISSUE TITLE
Cannot submit post

### ISSUE THREAD

**Issue by felixlehoang** [rvaidun/befake#19]
After the previous host migration, cannot submit post at all. If you could take a look at it that would be great, thank you.

**Comment by felixlehoang** [comment]
Tried with many different browsers, phones and laptop, but still not working.

**Comment by rvaidun** [comment]
pretty busy right now. if you need it fixed asap debug it and submit a pr :)

**Comment by colin-chadwick** [comment]
The error is here:  
`const uploadurl = this.$store.state.proxyUrl + res.headers.get("x-goog-upload-url"); `

It should be: 
 `const uploadurl =
          this.$store.state.proxyUrl +
          "/" +
          res.headers.get("x-goog-upload-url");`

**Comment by rvaidun** [comment]
thanks @colin-chadwick!
