### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by h4rqq** [rvaidun/befake#190]
Web not showing anything

**Comment by 083noah** [comment]
yes there is a new update, so its not working anymore! 

would be very great if you could do it this day, because i need to see the todays bereal bro

**Comment by Bastiaantjuhh** [comment]
**Debug**

Console log (browser dev tools) shows a error:
```
Failed to load resource: the server responded with a status of 403 (Forbidden)
```

CORS Anywhere. URL ```http://localhost:8080/https://mobile.bereal.com/api/feeds/friends-v1```
Response:
```
Missing required request header. Must specify one of: origin,x-requested-with
```
