### ISSUE TITLE
I hope that the king will update us soon

### ISSUE THREAD

**Issue by 11prasicc11** [rvaidun/befake#192]
_i hope bro you are working on updating, please save us_

**you are the king of mods** <333!!

Thank you bro :*

**Comment by NicoWeio** [comment]
It currently works for me at 6ae70ca3ecd8b90c1563c5d3939caa8326ce1f10, which has been committed just a few hours ago.

**Comment by nicospacez** [comment]
Adding these lines to all headers should fix this.

`'bereal-app-version-code': '14549',
'bereal-signature': 'berealsignature',
'bereal-device-id': 'berealdeviceid',`

**Comment by 11prasicc11** [comment]
@nicospacez can you help me how to start it or if there is a video on yt leave a link

**Comment by NicoWeio** [comment]
How about `npm run dev`?
It sounds like you need to get more familiar with the basics and it's impossible for me to briefly tell you at what point you need to start learning.

**Comment by NicoWeio** [comment]
Ah, that's a much more workable explanation.
Yesterday, I got BeFake to run using the same two commands, had the same layout issue on posts with many RealMojis (which I assume is unrelated), but did not try accessing the site using another device. If that's actually what you are asking for, and assuming this project uses Vite, try this:  https://github.com/vitejs/vite/discussions/3396 (add `--host` or find the correct place to do so).

**Comment by 11prasicc11** [comment]
@NicoWeio if I change the host, will I be able to react. Thanks man

**Comment by dertob** [comment]
After the update I can login again and pull up the fedd, thank you! But I can't fetch posts. I get an error-box in the bottom left stating just that. I only see the UI for posting myself. Is there a way I can provide you with more information that would help fixing it? Does it work for you guys?

**Comment by nicospacez** [comment]
Check the console output. Are all request fine or some errors there?
