### ISSUE TITLE
This still working?

### ISSUE THREAD

**Issue by Saiitama** [rvaidun/befake#201]
### Discussed in https://github.com/rvaidun/befake/discussions/200

<div type='discussions-op-text'>

<sup>Originally posted by **Saiitama** February 12, 2024</sup>
Hi i see people still postin here but i tought this project closed months ago? 
How do i use it? I had it on vercel but it stopped working, any other way?
(i'm really noob in these things)</div>

**Comment by Ein-Tim** [comment]
It recently stopped working again (a few days ago). Before that, you could use the source code provided in this repository to self-host.

**Comment by Saiitama** [comment]
just in case it re

> It recently stopped working again (a few days ago). Before that, you could use the source code provided in this repository to self-host.

just in case it start working again, how do i self host? any guide?

**Comment by starwarsman981** [comment]
I haven't heard a single person say anything besides for "it's probably gone forever" yet.

**Comment by Ein-Tim** [comment]
@Saiitama You could use Vercel for example, but I can (sadly) only second what @starwarsman981 said, due to the changes BeReal made it's unlikely that the project will work again (for a broad mass of people over a long period of time) so I'd suggest asking for a how-to again, should the project really come back.

**Comment by Ein-Tim** [comment]
FYI: For example https://github.com/s-alad/toofake is working again, same for BeFake (this repo for self hosting)

**Comment by Saiitama** [comment]
> FYI: For example https://github.com/s-alad/toofake is working again, same for BeFake (this repo for self hosting)

toofake is working, but i if selfhost this, when i put the number and press "send" (for the otp) it will keep on loading without sending anything, tried on different browser, with different devices

**Comment by Ein-Tim** [comment]
@Saiitama Did you pull the latest changes? Especially https://github.com/rvaidun/befake/commit/e54e0ec424d44d56375395e9b4dd3b39ee72c250 is important.

**Comment by Saiitama** [comment]
@Ein-Tim i deleted the repo i forked 1y ago and forked a new one 10 mins ago, then self hosted it on vercel (i'm not very good at this), but shouldn't this include the latest update?

**Comment by Ein-Tim** [comment]
Yep, it should. Then the root cause os something else.

**Comment by Saiitama** [comment]
@Ein-Tim so is it working for you if you self host it on vercel? can i test urs?

**Comment by Ein-Tim** [comment]
I'm not self hosting, sorry. I'm using too fake at the moment.

**Comment by rvaidun** [comment]
I think there is a bug with some non US numbers. Unfortunately, I only have a US number to test with

**Comment by Saiitama** [comment]
> I think there is a bug with some non US numbers. Unfortunately, I only have a US number to test with

I see, mine is Italian and doesn't work, can I help someonehow?

**Comment by Lauwy222** [comment]
Works!

**Comment by wilmxre** [comment]
@rvaidun i don't think it is a good idea to make the algorithm behind the signature public in this repo

**Comment by rvaidun** [comment]
@wilmxre have removed it

**Comment by Maximapple** [comment]
is it currently working? posts aren't loading for me. it was working yesterday.

**Comment by Maximapple** [comment]
now its loading posts again successfully. so odd.

**Comment by Maximapple** [comment]
and it stopped working again :(
