### ISSUE TITLE
Saving bereals locally !!!

### ISSUE THREAD

**Issue by SHADOW-13-WALKER** [rvaidun/befake#202]
Is there any way to save all your friends bereals locally ? beside saving them one by one !

I was thinking about saving every friend in a separate folder, with a separate folder for every day, and a folder of all the reactions !

I was running something similar using python but I don't know how to implement it in java ! can anyone help me with that please ? 

Thank you ^_^

**Comment by Saiitama** [comment]
Sorry to bother, is this currently working for u? If so from what country is your phone number?

**Comment by SHADOW-13-WALKER** [comment]
I'm using a Suisse phone number, hosting locally works fine for me!

**Comment by retoheusser** [comment]
> > I'm using a Suisse phone number, hosting locally works fine for me!
> 
> hosting locally without vercel? if so how?

Hosting locally probably refers to just running it locally as you were developing, by following the instructions in the readme. https://github.com/rvaidun/befake?tab=readme-ov-file#development-setup
I don't think this project uses any env variables you don't have, so you can do this.

**Comment by retoheusser** [comment]
For your original request, you could just run it locally and use a browser extension like https://chromewebstore.google.com/detail/download-all-images/ifipmflagepipjokmbdecpmjbibjnakm to download all images. 🤷🏽

**Comment by Saiitama** [comment]
> > > I'm using a Suisse phone number, hosting locally works fine for me!
> > 
> > 
> > hosting locally without vercel? if so how?
> 
> Hosting locally probably refers to just running it locally as you were developing, by following the instructions in the readme. https://github.com/rvaidun/befake?tab=readme-ov-file#development-setup I don't think this project uses any env variables you don't have, so you can do this.

hi, thanks i tried hosting on windows and it's working, anyway to host on android phone?
