### ISSUE TITLE
Is it possible to retrieve all old friends's posts?

### ISSUE THREAD

**Issue by mth-bou** [rvaidun/befake#205]
I was wondering if it was possible to retrieve all posts by friends, and friends of friends of a nickname, whether they are from today or from the past. 
At the moment, I have the impression that it's only possible to retrieve today's friends' posts.

Thanks in advance

**Comment by Ein-Tim** [comment]
Take a look at https://github.com/s-alad/toofake/issues/88. That's not possible.

**Comment by mth-bou** [comment]
> Take a look at [s-alad/toofake#88](https://github.com/s-alad/toofake/issues/88). That's not possible.

Okay, thanks for you quick reply !
