### ISSUE TITLE
Search for Profiles

### ISSUE THREAD

**Issue by rvaidun** [rvaidun/befake#22]
view whatever user profile you search up, not necessarily a friend. For instance if I wanted to search up “@djsjdjdjd” and have the profile picture pop up and any other information come up.

**Comment by xKRISTOFx** [comment]
it is partially implemented on hidden page

**Comment by xKRISTOFx** [comment]
> > it is partially implemented on hidden page
> 
> What's hidden page?

[here](https://befake.fr/search
)
