### ISSUE TITLE
Posting/Reaction Posting

### ISSUE THREAD

**Issue by h7ndrx** [rvaidun/befake#33]
Post feature and Reaction Upload not working, wish to see this working again you have the best dashboard so far!

**Comment by hubertoschusch** [comment]
> Thanks, BeReal updated their API and it is harder to upload photos to their server. Currently getting a 403 error when doing a PUT request to BeReal's API with the error unsigned payload. Not sure what this means or how to fix it. Please take a look at the attached screenshots. I've created a branch to work on this issue ![Screenshot 2023-02-01 at 11 33 59 AM](https://user-images.githubusercontent.com/19789246/216144955-94a6b58d-8c9e-463e-aded-8a2b6c778a6b.png)

Bereal indeed updated their API and now they use google signed urls with which you get access for a limited amount of time to the google cloud storage for uploading an image. I requested a pull on dominik-pm's fork where it is fixed already

**Comment by h7ndrx** [comment]
@hubertoschusch this fixes uploading of posts and realemoji reactions?

**Comment by hubertoschusch** [comment]
> @hubertoschusch this fixes uploading of posts and realemoji reactions?

yes

**Comment by rickyriii** [comment]
@rvaidun have you been able to test this?

**Comment by h7ndrx** [comment]
@hubertoschusch can you submit a pull request for this?

**Comment by traviewi** [comment]
has this been fixed? I see on his twitter he says its working, but when I login it still does not work
