### ISSUE TITLE
Login got changed

### ISSUE THREAD

**Issue by hubertoschusch** [rvaidun/befake#34]
Bereals login got changed and now they use recaptcha to verify that you are not a robot

**Comment by tadeasf** [comment]
yep, getting "INVALID_APP_CREDENTIAL" when trying to login. I can try to help if OP is still working on this project?

**Comment by s-alad** [comment]
> Bereals login got changed and now they use recaptcha to verify that you are not a robot

do you think there can be any bypass for this?

**Comment by h7ndrx** [comment]
@tadeasf yea i think he still working on it!

**Comment by tadeasf** [comment]
sure there is a solution. recaptha v2 isn't something new. just add the key to html head together with recaptha api and validate the reCAPTCHA response on the server-side when your form is submitted

**Comment by tadeasf** [comment]
I'm just not any good with Vue so I need to make sense of it, I'll then fork it and have a look

**Comment by h7ndrx** [comment]
great thank you! @tadeasf

**Comment by rvaidun** [comment]
marking this as closed. made changes to the login cloud function and site successfully sends OTP to phone number now instead of showing invalid app credentials
