### ISSUE TITLE
APP_NOT_VERIFIED on login

### ISSUE THREAD

**Issue by Bastkapp** [rvaidun/befake#35]
When trying to log in, befake shows Error: APP_NOT_VERIFIED
SMS with confirmation Code will be sent but webpage does not advance

**Comment by rvaidun** [comment]
Interesting, it is advancing for me. Maybe try doing a hard refresh on the site to clear the cache. I believe it's cmd + shift + r on mac or ctrl + shift + r on windows if you are using chrome or edge.

**Comment by Bastkapp** [comment]
I've treid that already. I've also tried it on multiple browsers (Chrome, Tor and Edge) And still, didn't work.
Maybe it has something to do with the country? Will try later with a VPN enabled, currently I get a TOO_MANY_ATTEMPTS_TRY_LATER which most likely is just a login log from the bereal api

**Comment by rvaidun** [comment]
Yes it is, I was getting the same 
TOO MANY ATTEMPTS error last night when debugging. I think it happens if you error too many times with the same phone number. I tried a different phone number and it worked.

**Comment by Bastkapp** [comment]
I've just found out, I am already connected on the browser of my phone. It probably saved it as a verified device. Will test tomorrow, if there may be too many devices connected (i.e. browser and app) so it wouldn't allow me to connect another

**Comment by Bastkapp** [comment]
After logging out on my phone, it still didn't work on my PC browser.
Now trying to log back in on my mobile browser, I get some Error like INVALID_CREDENTIALS_DETECTED

**Comment by Bastkapp** [comment]
The Error comes from us-central1-befake-623af.cloudfunctions.net/login and gives no other content.
The response is:
{
domain: "global",
​​​​message: "APP_NOT_VERIFIED",
​​reason: "invalid"
}

Its hard for me to further look into this, as I don't see, where the login is handled

**Comment by rvaidun** [comment]
https://gist.github.com/rvaidun/11e4ba2d61dd187586daf6c9b8172c65
At this gist is the code hosted on the cloud function, I have removed the values for fields specific to my device such as the appToken and deviceID.

**Comment by rvaidun** [comment]
Don't have a swiss phone number to test it with.

**Comment by Bastkapp** [comment]
With only the js, I personally can't directly see, where the error comes from. When using my personal number, I receive the VerificationCode, so there probably shouldn't be anything wrong with those requests.

As it is a 400 Error code, I suspect, there could be something wrong in the BeFake backend. Although I cannot say for certain.

**Comment by MomoCrafter2013** [comment]
Hi, I get the same error but my phone number is from the UK, +44. In my case, not even a SMS code is sent.

**Comment by Bastkapp** [comment]
Soo, I've just tried it again, and now I'm getting an ERROR: INVALID_APP_CREDENTIAL

**Comment by witchfindertr** [comment]
> ctrl + shift + r

yes working//

**Comment by 623maclan** [comment]
> Hi, I get the same error but my phone number is from the UK, +44. In my case, not even a SMS code is sent.

Same for uk number with +44

**Comment by rvaidun** [comment]
UK phone should be fixed now!

**Comment by MomoCrafter2013** [comment]
Hello, I get the same problem now with UK numbers +44

**Comment by Bastkapp** [comment]
Yes, it was working after the issue was closed.
Now it again has the same isste

**Comment by VxlerieUwU** [comment]
Hello @rvaidun Do you know how to get a valid appToken to get iosReceipt?

**Comment by FernandoSalmeron** [comment]
> UK phone should be fixed now!
@rvaidun 
Same problem now with Finland numbers +358

**Comment by FernandoSalmeron** [comment]
> UK phone should be fixed now!

@rvaidun
Same problem now with Finland numbers +358
