### ISSUE TITLE
Is it possible to view someone's post without being friends with them?

### ISSUE THREAD

**Issue by y1n0** [rvaidun/befake#37]
I inspected the network requests and their responses and I found that post images have this url form: `/Photos/[userId]/post/[imageId].webp` 

Is it possible to guess the `imageId` somehow?

**Comment by h7ndrx** [comment]
This would be cool wondering the same thing.

**Comment by rvaidun** [comment]
Agree with @ng2303, main reason I have not implemented this yet

**Comment by y1n0** [comment]
Don't get me wrong, I meant only if it is posted to public

**Comment by treehousekingcomic** [comment]
I third this
