### ISSUE TITLE
login down?

### ISSUE THREAD

**Issue by bengram** [rvaidun/befake#38]
Hello I can not log into befake

Is the login page down or is it me?

**Comment by ng2303** [comment]
i think login requires captcha now, unsure if that has been fixed in befake. users already logged in are unaffected I think

**Comment by bengram** [comment]
Be real use reCAPTCHA v3 now

https://developers.google.com/recaptcha/docs/v3

I think there is no more possibility to log in with new user
There should be an export account button immediately in befake to log in with it

**Comment by bengram** [comment]
login works :)

**Comment by rvaidun** [comment]
Login is not working for international users
