### ISSUE TITLE
React to all posts

### ISSUE THREAD

**Issue by Maximapple** [rvaidun/befake#39]
Hi, can you implement a feature that lets us react to all posts made by friends? For example, thumbs up on all posts.

Thanks!

**Comment by rvaidun** [comment]
This is a pretty good idea, I'll work on getting it out for the next major update.

**Comment by Maximapple** [comment]
Awesome! 

Keep in mind that there's some sort of rate limit, so once that's been reached, it'd be cool if the feature waits a few minutes and then continues where it left off.

**Comment by rvaidun** [comment]
Implemented

**Comment by Maximapple** [comment]
@rvaidun Looks good, thank you! Any way to use the existing reactions (thumbs up, heart eyes, etc.) to react to all of the posts, instead of adding a custom reaction to all posts?

**Comment by FreshImmuc** [comment]
> @rvaidun Looks good, thank you! Any way to use the existing reactions (thumbs up, heart eyes, etc.) to react to all of the posts, instead of adding a custom reaction to all posts?

Yes this would be great.

**Comment by Maximapple** [comment]
By the way, the feature in general doesn't seem to be working for me. It lets me upload a picture that should be used for the reaction and then I click on the "Upload RealMojis" button but nothing happens afterwards.

Uploading a custom RealMoji on a single BeReal post works just fine though.
