### ISSUE TITLE
uploading saved reactions

### ISSUE THREAD

**Issue by ng2303** [rvaidun/befake#40]
would you be able to add a feature for uploading saved reactions? like the heart, thumbs up, etc. i know you can upload the live/lightning one but still

**Comment by Maximapple** [comment]
that'd be awesome. if it's possible to do that, please also add support for saved reactions for the new reacting to all posts at once feature

**Comment by ggs3rvic3s** [comment]
the function already exists bit it is a bit hidden on mobile devices

**Comment by rvaidun** [comment]
added this feature recently
