### ISSUE TITLE
open source login cloud function

### ISSUE THREAD

**Issue by bengram** [rvaidun/befake#41]
Hello i am a big fan of your project..

I need the source code of the login cloud function :)

have a nice day

**Comment by rvaidun** [comment]
Login cloud function closed source for now just cuz there is personal device information such as appToken and deviceID and I believe those credentials to be unique to my device, don't want to expose the credentials but I have put it all in a gist
https://gist.github.com/rvaidun/11e4ba2d61dd187586daf6c9b8172c65
