### ISSUE TITLE
App not verified

### ISSUE THREAD

**Issue by 623maclan** [rvaidun/befake#44]
Keeps saying app not verified

**Comment by 623maclan** [comment]
Every time I put in my phone number and press send I get a app not verified message and it won't let me use it

**Comment by CyberTimon** [comment]
Same for me. I really want to use this but every time app not verified. +41 number (switzerland)

**Comment by rvaidun** [comment]
@CyberTimon pushed a fix it should work now
@623maclan what country is ur phone number?

**Comment by CyberTimon** [comment]
Thanks but now I get this: Error! Error: QUOTA_EXCEEDED : Too many recent phone auth attempts. Please try again later.
I test it again tomorrow
