### ISSUE TITLE
QUOTA_EXCEEDED

### ISSUE THREAD

**Issue by JLwebz** [rvaidun/befake#48]
If I try to connect more than one time, it'll display the error "Error! Error: QUOTA_EXCEEDED : Exceeded quota."

I tried once on Android then on my PC. I have a french number. It's just not working. 

Can you help ?

**Comment by ksigvaldason** [comment]
I've got same issue but I'm not even logged in on another instance

**Comment by TauTauwk** [comment]
I have the same problem I was logged out automatically and now see this error code as well I have a dutch number

**Comment by lanalsisada** [comment]
same happened to me, logged out automatically and can't log back in

**Comment by lanalsisada** [comment]
after reading up a bit on it on notmarek's repo, i learned that it should work after trying to log in a couple of times, worked for me

**Comment by ksigvaldason** [comment]
> after reading up a bit on it on notmarek's repo, i learned that it should work after trying to log in a couple of times, worked for me

So just typing your number in and hitting send repeatedly does the trick?

**Comment by lanalsisada** [comment]
> > after reading up a bit on it on notmarek's repo, i learned that it should work after trying to log in a couple of times, worked for me
> 
> So just typing your number in and hitting send repeatedly does the trick?

yeah, it worked for someone there and I tried it myself and worked on the ~6th try

**Comment by rvaidun** [comment]
yeah i get this issue too sometimes, usually goes away after a few tries
