### ISSUE TITLE
Uploading reaction broke if size is big?

### ISSUE THREAD

**Issue by Saiitama** [rvaidun/befake#51]
If i upload a reaction and the size it's "high" (don't know how much, probably more than 0,5 MB) it will upload a broken image, and in the app it will show a gray image

**Comment by rvaidun** [comment]
The maximum file size bereal accepts is 1048576 bytes
need to update the site to not accept images larger than this size or attempt to reduce the file size on the client side.

**Comment by Saiitama** [comment]
Just tried with 480kb, still doesn't work even tough is less than half the limit 

![IMG_20230415_215531](https://user-images.githubusercontent.com/22159233/232250710-5043dea1-87ac-4ec6-9093-842cd5f372a7.jpg)

**Comment by rvaidun** [comment]
1MB is the max file size for bereal posts and reactions. @Saiitama could you send the photo you tried to upload, 480kb should work

**Comment by Saiitama** [comment]
> 1MB is the max file size for bereal posts and reactions. @Saiitama could you send the photo you tried to upload, 480kb should work

Refreshing the page fixed it (without doing a new upload, the real image appeared instaed of the brokeb one I posted)
