### ISSUE TITLE
Deleting post doesn't work

### ISSUE THREAD

**Issue by xKRISTOFx** [rvaidun/befake#57]
![image](https://user-images.githubusercontent.com/74738911/231549396-9fd2cf56-d07a-4f1f-bfee-e02ca19da261.png)

**Comment by rvaidun** [comment]
I got around all CORS issues by spinning up my own cors anywhere server. https://github.com/Rob--W/cors-anywhere
Prefix the request with proxyURL value saved in the store.
![Screenshot 2023-04-14 at 7 30 57 PM](https://user-images.githubusercontent.com/19789246/232178917-24a2a553-cae0-4a0a-a69e-f97c308bd19b.png)
