### ISSUE TITLE
Site Not Found Why am I seeing this?

### ISSUE THREAD

**Issue by witchfindertr** [rvaidun/befake#78]
Site Not Found
Why am I seeing this?

**Comment by treehousekingcomic** [comment]
Same

**Comment by U14-dev** [comment]
Firebase issue, pretty sure sth fucked up with last deploy^

**Comment by Rafaeeeelllll** [comment]
Moi ça me met que le quota de messages est dépassé, c’est normal ?

**Comment by rvaidun** [comment]
Was migrating to a different firebase project and only moved the domain befake.fr and forgot to move www.befake.fr. Issue should be fixed now
