### ISSUE TITLE
QUOTA_EXCEEDED

### ISSUE THREAD

**Issue by akhileshbhaugeerutty** [rvaidun/befake#81]
Hi, 

Everything was working fine until today, but now I have the following error:
Error: QUOTA_EXCEEDED : Exceeded quota for sending verification codes.
I use a French phone (+33)
Thanks a lot and keep up the great work!

**Comment by Rafaeeeelllll** [comment]
La même

**Comment by Bryceshaw06** [comment]
Same here

**Comment by CAILLOUXX32** [comment]
Bonjour , moi aussi besoi daide pour le +33

**Comment by JackLeventreurreel** [comment]
Same

**Comment by danjer8** [comment]
Same
