### ISSUE TITLE
Quota exceeded and invalid app credentials

### ISSUE THREAD

**Issue by 623maclan** [rvaidun/befake#86]
Uk +44 numbers have both the errors

**Comment by JLwebz** [comment]
Same, for me, the error "Invalid app credentials" is constantly displayed, then "Quota exceeded". 
I have a (+33) French number.

**Comment by Naam8** [comment]
Same with +44. Haven't been able to log in for over a month.

**Comment by chkounhada** [comment]
Same thing for me (French +33 number)

**Comment by JackLeventreurreel** [comment]
Same for the french number (+33), tried everything, worked fine a week ago but it's been impossible to connect ever since

**Comment by rvaidun** [comment]
Please read #88
