### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ben-biber** [rvaidun/befake#93]
Error!
Something went wrong while getting posts

**Comment by fowled** [comment]
Seems like requesting public and friends feeds with the following endpoints now results in forbidden (403) requests, even with a valid token: `https://mobile.bereal.com/api/feeds/friends`, `https://mobile.bereal.com/api/feeds/discovery`

![image](https://user-images.githubusercontent.com/37367577/234309165-e10296b3-6b7e-4679-9e64-62a1c8ef406c.png)

**Comment by fowled** [comment]
Tried to proxy my phone via MITMproxy to try and get the new endpoints with correct parameters and auth settings, but it looks like they've implemented certificate pinning, which makes it impossible to even load the app while proxied... is this the end?

**Comment by stepersy** [comment]
Let's hope not

**Comment by stepersy** [comment]
Let's hope not

**Comment by U14-dev** [comment]
Yea, same for my private wrapper. Getting 401 even with a fresh created token... i guess they try to block stuff like this

**Comment by U14-dev** [comment]
> Tried to proxy my phone via MITMproxy to try and get the new endpoints with correct parameters and auth settings, but it looks like they've implemented certificate pinning, which makes it impossible to even load the app while proxied... is this the end?

As far as i know they use cert pinning since quite a while, makes logging a lot more difficult  but not impossible if someone is motivated enough

**Comment by ESPMAXI2378** [comment]
Is gone 😞

**Comment by xKRISTOFx** [comment]
[*]

**Comment by rvaidun** [comment]
BeReal did implement Certificate pinning. I have been able to get around it with a jailbroken device and SSL Kill Switch 2, a jailbreak tweak that disables pinning. https://github.com/nabla-c0d3/ssl-kill-switch2

**Comment by U14-dev** [comment]
Nice one, gonna look into it. Ty^

**Comment by stepersy** [comment]
So, no more website?

**Comment by xKRISTOFx** [comment]
> BeReal did implement Certificate pinning. I have been able to get around it with a jailbroken device and SSL Kill Switch 2, a jailbreak tweak that disables pinning. https://github.com/nabla-c0d3/ssl-kill-switch2

Looks promising 👌

**Comment by mewtonthebeat** [comment]
https://github.com/notmarek/BeFake/pull/80#issue-1683840158

**Comment by rvaidun** [comment]
https://github.com/rvaidun/befake/pull/98

**Comment by rvaidun** [comment]
Fixed by #98
